# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b28d46de40378fc2eb5f0cb00c29520b94339365876d48ce7967c025b2a72efd9f8303713751bf4d31e7b14e4ee44c539f14caed30b2512370d7fba263ca2a02

test:
  secret_key_base: 9edfbbc57f49c0e34454a5ef718ace3c78cec9015682da06ed015859fad7f03fdfd4b137dfbe505496daf437f3c8bccd252edd9e9b88dbcf1a40424e16a2996c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
